name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name}}
on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'The environment to deploy to'
        type: string
      version:
        required: true
        description: 'The version to deploy'
        type: string
      helm-values-path:
        type: string
        default: './todoapp/values.yaml'
      helm-release-name:
        type: string
        default: 'todoapp'
jobs:
    deploy-to-k8s:
      name: Deploy to K8s
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}

      steps:
      - uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AZURE_RESOURSE_GROUP }}
          cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}

      - name: Helm Dry Run / Validate
        run: |
          helm install todoapp-staging ./todoapp-*.tgz \
            --dry-run \
            --debug \
            -f ${{ inputs.helm-values-path }} \
            --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
            --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
            --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
            --set todoapp.image.version="${{ github.sha }}"

      - name: Deploy Helm
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
            -f ${{ inputs.helm-values-path}} \
            --set mysql.secrets.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.secrets.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.secrets.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set todoapp.secrets.SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            --set todoapp.secrets.DB_NAME="${{ secrets.DB_NAME }}" \
            --set todoapp.secrets.DB_USER="${{ secrets.DB_USER }}" \
            --set todoapp.secrets.DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --set todoapp.secrets.DB_HOST="${{ secrets.DB_HOST }}" \
            --set todoapp.image.version="${{ github.sha }}"